"""
dashboard/app.py — Streamlit dashboard for Boxing AI Performance Analyzer.

Launch with:
    streamlit run dashboard/app.py

The dashboard reads the outputs written by the main pipeline:
    - outputs/fight_summary.json  → aggregate fight stats
    - outputs/fight_stats.csv     → per-frame data for charts

It does NOT re-run the video pipeline.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Boxing AI Analyzer",
    page_icon="🥊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Paths (relative to project root; works when launched from any CWD) ────────
_HERE  = Path(__file__).resolve().parent          # dashboard/
_ROOT  = _HERE.parent                             # project root
OUTPUT = _ROOT / "outputs"
JSON_PATH = OUTPUT / "fight_summary.json"
CSV_PATH  = OUTPUT / "fight_stats.csv"


# ─────────────────────────────────────────────────────────────────────────────
# Data loading helpers
# ─────────────────────────────────────────────────────────────────────────────

@st.cache_data
def load_summary(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


@st.cache_data
def load_frame_data(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar
# ─────────────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.image("https://img.icons8.com/emoji/96/boxing-glove.png", width=64)
    st.title("Boxing AI")
    st.caption("Performance Analyzer")
    st.divider()

    if st.button("🔄 Refresh data"):
        st.cache_data.clear()

    st.markdown("### About")
    st.markdown(
        "This dashboard visualises fight analysis results "
        "generated by `python main.py`."
    )
    st.divider()
    st.caption("Run `streamlit run dashboard/app.py` from the project root.")


# ─────────────────────────────────────────────────────────────────────────────
# Main content
# ─────────────────────────────────────────────────────────────────────────────

st.title("🥊 Boxing AI Performance Analyzer")
st.markdown("---")

summary = load_summary(JSON_PATH)
df      = load_frame_data(CSV_PATH)

# ── No data state ─────────────────────────────────────────────────────────────
if not summary:
    st.warning(
        "**No analysis results found.**\n\n"
        "Run the pipeline first:\n"
        "```bash\n"
        "python main.py --video data/fight.mp4\n"
        "```\n"
        "Then refresh this page."
    )
    st.stop()

fighters = summary.get("fighters", {})
n_frames = summary.get("total_frames_processed", 0)

# ─────────────────────────────────────────────────────────────────────────────
# Top KPIs
# ─────────────────────────────────────────────────────────────────────────────

st.subheader("📊 Fight Overview")
kpi_cols = st.columns(len(fighters) * 3 + 1)

kpi_cols[0].metric("Frames Analysed", f"{n_frames:,}")

for i, (fid, stats) in enumerate(fighters.items()):
    base = i * 3 + 1
    label = f"Fighter {stats['track_id']}"
    kpi_cols[base + 0].metric(f"🥊 {label} — Punches", stats["total_punches"])
    kpi_cols[base + 1].metric(f"🛡 {label} — Guards",   stats["guards"])
    kpi_cols[base + 2].metric(f"📐 {label} — Distance", f"{stats['total_distance_px']:.0f} px")

st.markdown("---")

# ─────────────────────────────────────────────────────────────────────────────
# Punch breakdown (side by side)
# ─────────────────────────────────────────────────────────────────────────────

st.subheader("🥊 Punch Breakdown per Fighter")
punch_cols = st.columns(len(fighters))

for col, (fid, stats) in zip(punch_cols, fighters.items()):
    labels  = ["Jab", "Cross", "Hook", "Uppercut"]
    values  = [stats["jabs"], stats["crosses"], stats["hooks"], stats["uppercuts"]]
    fig = px.pie(
        values=values,
        names=labels,
        title=f"Fighter {stats['track_id']} — Punch Distribution",
        color_discrete_sequence=px.colors.sequential.Plasma_r,
        hole=0.4,
    )
    fig.update_traces(textinfo="label+percent")
    col.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ─────────────────────────────────────────────────────────────────────────────
# Defense breakdown
# ─────────────────────────────────────────────────────────────────────────────

st.subheader("🛡 Defensive Actions per Fighter")
def_data = []
for fid, stats in fighters.items():
    for action in ("guards", "slips", "ducks", "clinches"):
        def_data.append({
            "Fighter": f"F{stats['track_id']}",
            "Action": action.capitalize(),
            "Count": stats[action],
        })

if def_data:
    def_df = pd.DataFrame(def_data)
    fig_def = px.bar(
        def_df,
        x="Action",
        y="Count",
        color="Fighter",
        barmode="group",
        title="Defensive Actions Comparison",
        color_discrete_sequence=["#7C3AED", "#F59E0B"],
    )
    st.plotly_chart(fig_def, use_container_width=True)

st.markdown("---")

# ─────────────────────────────────────────────────────────────────────────────
# Frame-level time series (only if CSV data is available)
# ─────────────────────────────────────────────────────────────────────────────

if not df.empty:
    st.subheader("📈 Frame-Level Analysis")

    tab1, tab2, tab3 = st.tabs(["Arm Extension", "Movement (Position)", "Torso Lean"])

    with tab1:
        fighter_ids = df["track_id"].unique()
        ext_df = df.copy()
        # Mean extension (left + right) per frame per fighter
        ext_df["mean_extension"] = (ext_df["left_ext"] + ext_df["right_ext"]) / 2
        fig_ext = px.line(
            ext_df,
            x="frame_idx",
            y="mean_extension",
            color="track_id",
            title="Mean Arm Extension Over Time",
            labels={"frame_idx": "Frame", "mean_extension": "Arm Extension Ratio", "track_id": "Fighter"},
            color_discrete_sequence=["#10B981", "#F97316"],
        )
        st.plotly_chart(fig_ext, use_container_width=True)

    with tab2:
        fig_pos = px.scatter(
            df,
            x="center_x",
            y="center_y",
            color="track_id",
            title="Fighter Position Heatmap",
            labels={"center_x": "X (px)", "center_y": "Y (px)", "track_id": "Fighter"},
            opacity=0.3,
            color_discrete_sequence=["#10B981", "#F97316"],
        )
        fig_pos.update_yaxes(autorange="reversed")   # image Y axis goes downward
        st.plotly_chart(fig_pos, use_container_width=True)

    with tab3:
        fig_lean = px.line(
            df,
            x="frame_idx",
            y="torso_lean",
            color="track_id",
            title="Torso Lean Angle Over Time",
            labels={"frame_idx": "Frame", "torso_lean": "Lean (°)", "track_id": "Fighter"},
            color_discrete_sequence=["#10B981", "#F97316"],
        )
        fig_lean.add_hline(y=0, line_dash="dot", line_color="white", opacity=0.3)
        st.plotly_chart(fig_lean, use_container_width=True)

    st.markdown("---")

    # ── Strike timeline ────────────────────────────────────────────────────
    st.subheader("⚡ Strike Timeline")
    strike_df = df[df["strike_label"] != "NONE"].copy()
    if not strike_df.empty:
        fig_strikes = px.scatter(
            strike_df,
            x="frame_idx",
            y="track_id",
            color="strike_label",
            symbol="strike_label",
            title="Punch Events Over Time",
            labels={"frame_idx": "Frame", "track_id": "Fighter", "strike_label": "Punch"},
            color_discrete_map={
                "JAB":      "#60A5FA",
                "CROSS":    "#F87171",
                "HOOK":     "#FBBF24",
                "UPPERCUT": "#A78BFA",
            },
        )
        st.plotly_chart(fig_strikes, use_container_width=True)
    else:
        st.info("No punch events detected in this analysis.")

    st.markdown("---")

    # ── Raw frame data table ───────────────────────────────────────────────
    with st.expander("🗃 Raw Frame Data"):
        st.dataframe(df, use_container_width=True, height=300)

# ─────────────────────────────────────────────────────────────────────────────
# Aggression comparison
# ─────────────────────────────────────────────────────────────────────────────

st.subheader("🔥 Aggression Index")
agg_data = [
    {
        "Fighter": f"Fighter {stats['track_id']}",
        "Aggression": stats["aggression_score"],
    }
    for stats in fighters.values()
]
agg_df = pd.DataFrame(agg_data)
fig_agg = px.bar(
    agg_df,
    x="Fighter",
    y="Aggression",
    title="Aggression Score (Punches / Frames Detected)",
    color="Aggression",
    color_continuous_scale="Plasma",
)
st.plotly_chart(fig_agg, use_container_width=True)

st.markdown("---")
st.caption("Boxing AI Performance Analyzer — powered by Ultralytics YOLOv8 Pose + BoT-SORT")
